Eliminate conflict with OpenBSD's swap32 macro
blowfish-bcrypt.c:152:33: error: too many arguments provided to function-like macro invocation
static void swap32(uint32_t *x, int count)
                                ^
/usr/include/sys/endian.h:71:9: note: macro 'swap32' defined here

Signed-off-by: Brad Smith <brad@comstyle.com>